apiVersion: v1
kind: Service
metadata:
  name: mongodb-pharmacy
spec:
  selector:
    app: mongodb-pharmacy
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-pharmacy
spec:
  selector:
    matchLabels:
      app: mongodb-pharmacy
  template:
    metadata:
      labels:
        app: mongodb-pharmacy
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: storage
      volumes:
        - name: storage
          emptyDir: {}
