apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-billing-config
data:
  POSTGRES_DB: billing_db
  POSTGRES_USER: billing_user
  POSTGRES_PASSWORD: billing_pass
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-billing
spec:
  selector:
    app: postgres-billing
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-billing
spec:
  selector:
    matchLabels:
      app: postgres-billing
  template:
    metadata:
      labels:
        app: postgres-billing
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-billing-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: storage
      volumes:
        - name: storage
          emptyDir: {}
